#------- COMMENT to enable a rule, UNCOMMENT to disable: -------#
#-------    these rules are usually enabled by default   -------#
disabled_rules:

# List of rules: https://github.com/realm/SwiftLint/blob/master/Rules.md

#--- Stylistic rules ---#
- syntactic_sugar
- control_statement
- identifier_name
- trailing_whitespace
#- opening_brace
#- vertical_whitespace
#- statement_position
#- trailing_newline
#- empty_enum_arguments
#- implicit_getter
#- trailing_semicolon
#- legacy_constructor
#- return_arrow_whitespace
#- shorthand_operator
#- vertical_parameter_alignment
#- leading_whitespace
#- mark
#- operator_whitespace
#- closing_brace
#- compiler_protocol_init
#- redundant_void_return
#- generic_type_name
#- attributes
#- closure_parameter_position
#- trailing_comma
#- empty_parentheses_with_trailing_closure

#--- Hygienic rules ---#
- function_body_length
- line_length
- type_body_length
- file_length

#--- Convention rules ---#
- redundant_string_enum_value
- unused_optional_binding
- unused_closure_parameter
- type_name
- for_where
- colon
#- comma
#- redundant_optional_initialization
#- unused_enumerated
#- redundant_discardable_let
#- legacy_cggeometry_functions
#- legacy_nsgeometry_functions
#- private_over_fileprivate
#- protocol_property_accessors_order
#- empty_parameters
#- void_return
#- legacy_constant

#--- Code smell rules ---#
- function_parameter_count
- force_cast
- cyclomatic_complexity
- nesting
- todo
- large_tuple
- force_try

#--- Bug avoiding rules ---#
- valid_ibinspectable
- notification_center_detachment
#- discarded_notification_center_observer
#- class_delegate_protocol
#- dynamic_inline
#- weak_delegate
#- private_unit_test
#- private_outlet

#--- Others ---#
- custom_rules # for custom rules check https://github.com/realm/SwiftLint


#------- UNCOMMENT to enable a rule, COMMENT to disable: -------#
#-------   these rules are usually disabled by default   -------#
opt_in_rules:

#--- Stylistic rules ---#
#- vertical_parameter_alignment_on_call
#- closure_end_indentation
#- conditional_returns_on_newline
#- let_var_whitespace
#- number_separator
#- switch_case_on_newline
#- unneeded_parentheses_in_closure_argument
- operator_usage_whitespace
- closure_spacing
- multiline_parameters

#--- Convention rules ---#
#- explicit_init
#- explicit_top_level_acl
#- file_header
#- implicit_return
#- nimble_operator

#--- Code smell rules ---#
#- force_unwrapping

#--- Bug avoiding rules ---#
#- empty_count
#- overridden_super_call
#- prohibited_super_call
- fatal_error_message

#--- Other rules ---#
#- explicit_type_interface
#- extension_access_modifier
#- first_where
#- implicitly_unwrapped_optional
#- no_extension_access_modifier
#- object_literal
#- redundant_nil_coalescing
#- sorted_imports
#- strict_fileprivate


#------- Other configurations -------#
excluded:
  - Carthage

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
